// lib/schemas/historiaClinicaSchema.ts
// Esquema Zod de la Historia Clínica (NOM-004-SSA3-2012).
// Separado del componente para reutilización y mejor organización.

import * as z from 'zod'

export const historiaClinicaSchema = z.object({
  ficha_identificacion: z.object({
    nombre_completo: z.string().min(1, 'El nombre es obligatorio'),
    fecha_nacimiento: z.string().min(1, 'La fecha de nacimiento es obligatoria'),
    genero: z.string().min(1, 'El género es obligatorio'),
    edad: z.string().optional(),
    grupo_sanguineo: z.string().optional(),
    estado_civil: z.string().optional(),
    nacionalidad: z.string().optional(),
    lugar_nacimiento: z.string().optional(),
    direccion: z.string().optional(),
    escolaridad: z.string().optional(),
    ocupacion: z.string().optional(),
    persona_responsable: z.string().optional(),
  }),
  antecedentes_heredo_familiares: z.string().optional(),
  antecedentes_personales_no_patologicos: z.object({
    alimentacion: z.string().optional(),
    vivienda: z.string().optional(),
    habitos_higienicos_individuales: z.string().optional(),
    tiempo_libre: z.string().optional(),
    inmunizaciones: z.string().optional(),
  }),
  antecedentes_personales_patologicos: z.object({
    infectocontagiosos: z.string().optional(),
    enfermedades_exantematicas: z.string().optional(),
    enfermedades_cronico_degenerativas: z.string().optional(),
    alergias: z.string().optional(),
    quirurgicos: z.string().optional(),
    traumaticos: z.string().optional(),
    convulsivos: z.string().optional(),
    transfusiones: z.string().optional(),
    drogas: z.string().optional(),
    hospitalizaciones_previas: z.string().optional(),
    exposicion_a_biomasa: z.string().optional(),
    factores_de_riesgo_cardiovascular: z.string().optional(),
  }),
  antecedentes_gineco_obstetricos: z.object({
    menarca: z.string().optional(),
    ritmo_menstrual: z.string().optional(),
    fur: z.string().optional(),
    gesta: z.string().optional(),
    partos: z.string().optional(),
    cesareas: z.string().optional(),
    abortos: z.string().optional(),
    fup: z.string().optional(),
    metodo_anticonceptivo: z.string().optional(),
    menopausia: z.string().optional(),
    colposcopia_previa: z.string().optional(),
  }).optional(),
  padecimiento_actual: z.string().optional(),
  interrogatorio_aparatos_sistemas: z.object({
    aparato_respiratorio: z.string().optional(),
    aparato_cardiovascular: z.string().optional(),
    aparato_digestivo: z.string().optional(),
    aparato_renal_urinario: z.string().optional(),
    aparato_genital: z.string().optional(),
    endocrino: z.string().optional(),
    hematologico: z.string().optional(),
    piel_y_anexos: z.string().optional(),
    musculo_esqueletico: z.string().optional(),
    sistema_nervioso_central: z.string().optional(),
    organo_de_los_sentidos: z.string().optional(),
    esfera_psiquica: z.string().optional(),
    sintomas_generales: z.string().optional(),
  }),
  exploracion_fisica: z.object({
    signos_vitales: z.object({
      talla: z.string().optional(),
      peso: z.string().optional(),
      imc: z.string().optional(),
      fc: z.string().optional(),
      temperatura: z.string().optional(),
      fr: z.string().optional(),
      tension_arterial: z.string().optional(),
      saturacion: z.string().optional(),
    }),
    habitus_exterior: z.string().optional(),
    neurologico: z.string().optional(),
    cabeza: z.string().optional(),
    cara: z.string().optional(),
    ojos: z.string().optional(),
    oido: z.string().optional(),
    nariz: z.string().optional(),
    cavidad_bucal: z.string().optional(),
    cuello: z.string().optional(),
    torax: z.string().optional(),
    region_precordial: z.string().optional(),
    abdomen: z.string().optional(),
    genitales_externos: z.string().optional(),
    extremidades: z.string().optional(),
  }),
  examenes_previos: z.string().optional(),
  diagnosticos: z.string().optional(),
  plan_y_tratamiento: z.string().optional(),
  pronostico: z.string().optional(),
})

export type HistoriaClinicaFormData = z.infer<typeof historiaClinicaSchema>
